---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
spec:
  project: default
  source:
    repoURL: "https://github.com/shrapk2/awx-operator-helm"
    path: awx/
    targetRevision: argod-dev
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
