---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
      {{- include "awx-operator.labels" . | nindent 4 }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: awx-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    -  {{ .Values.network.hostname }}
    port:
      name: http
      number: 80
      protocol: HTTP