---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    {{- include "awx-operator.labels" . | nindent 4 }}
  name: awx-operator-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager